[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
dotenv = "0.15.0"
diesel = {version = "2.2.1", features = ["sqlite", "chrono"]}
chrono = {version = "0.4.38", features = ["serde"]}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.117"